# PCA/SVD

结论:实对称阵的不同特征值对应的特征向量一定是正交的
求方差最大化的PCA：先求A的协方差矩阵，然后对该矩阵求他的特征值和特征向量，取前K个特征值即可
PCA应用
- 去噪
- 降维

当XY独立时，$E(XY)=E(X)E(Y)$

而 $Cov(X,Y)=E(XY)-E(X)E(Y)$

从而当XY独立时，他们之间的协方差为0，可称为XY不想关

协方差的上界
$Var(Y)=\sigma_2^2,Var(X)=\sigma_1^2$

则$|Cov(X,Y)|<=\sigma_1\sigma_2$



相关系数：标准化后的协方差

探究相关系数和向量夹角的关系：其实文档之间用夹角余弦是因为这一物理量表征了文档去均值化之后的随机变量间的相关系数 
---
 

In [1]:
from sklearn.decomposition import PCA
import numpy as np
X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
pca = PCA(n_components='mle',copy=True,whiten=False)
pca.fit(X)

PCA(copy=True, iterated_power='auto', n_components='mle', random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [2]:
pca.components_

array([[-0.83849224, -0.54491354]])

In [3]:
pca.explained_variance_ratio_

array([0.99244289])

In [4]:
pca.n_components_

1

In [5]:
pca.n_components

'mle'

In [6]:
pca.transform(X)

array([[ 1.38340578],
       [ 2.22189802],
       [ 3.6053038 ],
       [-1.38340578],
       [-2.22189802],
       [-3.6053038 ]])

# SVD
在矩阵A的奇异值分解中 $A=U \Sigma V^T$
U的列组成一族对A的正交输入或分析的基向量，这些向量也是$A A^T$的特征向量，
V的咧组成一族对A的正交输出的基向量，这些向量是$A^T A$的特征向量，
$\Sigma$的对角线上的元素是奇异值，可视为是在输入和输出之间进行的标量的膨胀控制，这是$A^TA 与 A A^T$的奇异值，并于U和V的列向量对应 

实际中，往往只保留$\Sigma$中前K个较大的数

PLSA（主题模型） 可以看作概率化的矩阵分解

In [8]:
import numpy as np
from numpy.linalg import svd
A = np.array([[1,2],[1,0]])

In [9]:
u,s,v=svd(A)

In [12]:
print(u)
print(s)
print(v)

[[-0.97324899 -0.22975292]
 [-0.22975292  0.97324899]]
[2.28824561 0.87403205]
[[-0.52573111 -0.85065081]
 [ 0.85065081 -0.52573111]]
